# | Local Variable        | Result                                                                                                                                                         | Explanation                                         |
# | --------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------- |
# | `external_ip_add`     | `1`                                                                                                                                                            | Because `enable_external_ip = true`                 |
# | `access_config`       | `[true]`                                                                                                                                                       | External IP enabled                                 |
# | `shielded_vm_configs` | `[]`                                                                                                                                                           | Disabled (`enable_shielded_vm = false`)             |
# | `instance_name`       | `["web1", "web2", "web3"]`                                                                                                                                     | Three VM names                                      |
# | `disk_name`           | `[["web1-persistent-disk1", "web1-persistent-disk2"], ["web2-persistent-disk1", "web2-persistent-disk2"], ["web3-persistent-disk1", "web3-persistent-disk2"]]` | Nested list (disks per VM)                          |
# | `attached_disk_names` | `["web1-persistent-disk1", "web1-persistent-disk2", "web2-persistent-disk1", "web2-persistent-disk2", "web3-persistent-disk1", "web3-persistent-disk2"]`       | Flattened list of all disk names                    |
# | `instance`            | `["web1", "web1", "web2", "web2", "web3", "web3"]`                                                                                                             | Each instance repeated for each of its disks        |
# | `zones`               | `["us-central1-a", "us-central1-a", "us-central1-b", "us-central1-b", "us-central1-a", "us-central1-a"]`                                                       | Zones assigned in round-robin per instance per disk |
